Allow to choose the color
sebbmeyer/php-microsoft-teams-connector pull request #2
Opened 2018-10-26 10:45 UTC by janvernieuwe

Make it so the color can be set in the SimpleCard

2018-11-23 12:25 UTC, janvernieuwe commented
Poke? Can we get this merged?

2018-12-05 16:16 UTC, sebbmeyer commented
I should update my emails settings to this request

2018-12-05 16:26 UTC, sebbmeyer requested changes
looks good so far but it's need a little adjustment, but then it's a go

2018-12-05 16:26 UTC, sebbmeyer commented on src/Cards/SimpleCard.php
> +            "themeColor" => isset($this->data['themeColor']) ? $this->data['themeColor'] : "0072C6",
We should check if `themeColor` is not an empty string, but than we can merged it

```suggestion
            "themeColor" => !empty($this->data['themeColor']) ? $this->data['themeColor'] : "0072C6",
```

2018-12-05 17:51 UTC, janvernieuwe commented
Alright, that change looks good to me, thanks for looking at it!

2018-12-05 18:02 UTC, sebbmeyer approved these changes

2018-12-05 18:02 UTC, merged